### ISSUE TITLE
Exclude directories

### ISSUE THREAD

**Issue by ocumo** [israel-lugo/capidup#10]
Hi,
Just a suggestion:
It would be useful to have an option to exclude directories. This would make it even more flexible.
Thanks a lot for this nice tool !!

**Comment by israel-lugo** [comment]
Hi there,

That's a good idea! I will implement it in the next release.

Thanks for the suggestion.

**Comment by ocumo** [comment]
Thanks!
I actually have another idea, I 'll open another issue, then.
regards

**Comment by israel-lugo** [comment]
Perhaps it would also be useful to exclude files, either by name or by glob pattern (```*.zip``` and so on).

**Comment by ocumo** [comment]
Well, now that you mention it, that looks like the next thing to ask...
and since we are there, if that's not abusing: what about regular expressions? 
Regexes are always on the "advanced user" side, and in this context it may not be the more obvious use case as well, so priority for something like that might fit in the 'nice to have' instead?
