### ISSUE TITLE
Make find_duplicates_in_dirs() return list of errors

### ISSUE THREAD

**Issue by ocumo** [israel-lugo/capidup#11]
Currently, capidup.finddups.find_duplicates_in_dirs() returns a boolean to tell if there were any errors.
Do you have plans to have this function returning a list of those errors?
Thanks

**Comment by israel-lugo** [comment]
You're right, that doesn't provide much useful information. The reason for that is mostly historical: the errors are printed to stderr as they are found, which makes sense for the command-line utility [capidup-cli](https://github.com/israel-lugo/capidup-cli). Of course, for other programs it may not be sufficient.

I'll change that before the 1.0 release, perhaps returning a list of error strings. There are multiple possibilities for error: e.g. an I/O error while calculating the MD5 for a file, or a permissions error while recursing through the directories...

I see two possibilities: either a list of error strings, or I could actually create some kind of CapiDupError class, with a structured approach (error.file, error.reason, etc). Basically, a list of exceptions... Not sure if that's worth it.

**Comment by ocumo** [comment]
I think that while returning a fancy object with such properties would be nice for playing around in a program that would use CapiDup, it would be a bit of overkill, as the main thing should be the detection of dupes and its reliability, speed, etc. and not so much a very flexible and powerful API for error handling.   Eventually, such approach could be something for much later if people would really think this is for some reason convenient.  I'd vote, thus, for a simple list.
Many thanks !

**Comment by israel-lugo** [comment]
Yup, I'll go with a simple list of error strings. Can always change in the future if something fancy really becomes necessary.

**Comment by ocumo** [comment]
Nice!
Sounds like a great plan!

**Comment by israel-lugo** [comment]
I'm wondering whether the API should stop printing errors to stderr as they happen. I don't see much harm in printing them, but it may be undesirable for some programs.

The downside is that errors will no longer be reported in real-time, but only when find_duplicates_in_dirs() returns.

**Comment by israel-lugo** [comment]
Idea for the future: new optional parameter `on_error`. If specified, it should be a function, which will be called when an error occurs, with one argument: a CapiDupIOError instance. The function can either return or raise the CapiDupIOError exception to abort execution.

This way, programs can react immediately to errors (e.g. report them in a graphical manner) and, if necessary, abort.

Leave this for some future major version.
